/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CareerSuggestion = IDL.Record({
  'projectIdeas' : IDL.Vec(IDL.Text),
  'skillRoadmap' : IDL.Vec(IDL.Text),
  'resumeTips' : IDL.Vec(IDL.Text),
  'studyPlan' : IDL.Vec(IDL.Text),
  'internshipDomains' : IDL.Vec(IDL.Text),
});
export const StudentProfile = IDL.Record({
  'id' : IDL.Text,
  'branch' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const AttendanceInput = IDL.Record({
  'totalClasses' : IDL.Nat,
  'attendedClasses' : IDL.Nat,
  'remainingClasses' : IDL.Nat,
});
export const AttendanceRisk = IDL.Record({
  'classesNeeded' : IDL.Nat,
  'riskLevel' : IDL.Text,
  'percentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCareerSuggestion' : IDL.Func([IDL.Text, CareerSuggestion], [], []),
  'addStudent' : IDL.Func([StudentProfile], [], []),
  'calculateAttendanceRisk' : IDL.Func(
      [AttendanceInput],
      [AttendanceRisk],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCareerSuggestion' : IDL.Func([IDL.Text], [CareerSuggestion], ['query']),
  'getStudentProfile' : IDL.Func([IDL.Text], [StudentProfile], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CareerSuggestion = IDL.Record({
    'projectIdeas' : IDL.Vec(IDL.Text),
    'skillRoadmap' : IDL.Vec(IDL.Text),
    'resumeTips' : IDL.Vec(IDL.Text),
    'studyPlan' : IDL.Vec(IDL.Text),
    'internshipDomains' : IDL.Vec(IDL.Text),
  });
  const StudentProfile = IDL.Record({
    'id' : IDL.Text,
    'branch' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const AttendanceInput = IDL.Record({
    'totalClasses' : IDL.Nat,
    'attendedClasses' : IDL.Nat,
    'remainingClasses' : IDL.Nat,
  });
  const AttendanceRisk = IDL.Record({
    'classesNeeded' : IDL.Nat,
    'riskLevel' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCareerSuggestion' : IDL.Func([IDL.Text, CareerSuggestion], [], []),
    'addStudent' : IDL.Func([StudentProfile], [], []),
    'calculateAttendanceRisk' : IDL.Func(
        [AttendanceInput],
        [AttendanceRisk],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getCareerSuggestion' : IDL.Func([IDL.Text], [CareerSuggestion], ['query']),
    'getStudentProfile' : IDL.Func([IDL.Text], [StudentProfile], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };